### ISSUE TITLE
很喜欢这个主题，能用Hexo使用这种主题嘛

### ISSUE THREAD

**Issue by Sum41forever** [wuyouzhuguli/Conciseness#1]
说一下 抓音乐用网易云的MP3 外链不太好。以前那种方式已经不好用了。
推荐用这个网页来抓，用酷狗的源http://music.liuzhijin.cn/

**Comment by Sum41forever** [comment]
还有markdown的显示好像有点问题，我预览是可以正常看的，但是实际显示有写问题。
比如这个的markdown里面显示就有点问题
http://www.sum41forever.com/post/5c5e110400c2

**Comment by wuyouzhuguli** [comment]
@Sum41forever 
你说的是代码过长不换行的问题么？是的话可以修改style.css，664行：
```css
code {
    white-space: pre-wrap;
}
```
网易云的外链好像很早就关了，你推荐的这个网址不错&#128522;
--

**Comment by Sum41forever** [comment]
不是换行的问题， 如果markdown写代码
换行以后 缩进好像有点不对。你看return没有缩进了。其他的页面也是这样的

![image](https://user-images.githubusercontent.com/18468976/35154604-c214bfcc-fd65-11e7-91fe-4b714efbc115.png)
