### ISSUE TITLE
一进入Blog自动播放音乐如何处理

### ISSUE THREAD

**Issue by Sum41forever** [wuyouzhuguli/Conciseness#2]
在player.js 里弄了半天 还是不行，求指教。
完全不懂Web端。。

**Comment by wuyouzhuguli** [comment]
现在浏览器好像大部分都进制自动播放了。
https://developers.google.com/web/updates/2017/09/autoplay-policy-changes

**Comment by Sum41forever** [comment]
诶 还有一个问题，点哪个Toc生成的目录没法跳转到对应的标题去了。

**Comment by Sum41forever** [comment]
今天发现又好了。 Toc生成的目录可以跳转 汗
